import type { GameView, ObservabilityView } from '../application/game-view';
import { presentationCatalog } from '../application/presentation-catalog';
import { number, pct } from './game-format';
import { PageHeading } from './game-panel';

export function FeatureBoard({ view, observability, onFastTrack, onRefactor }: { view: GameView; observability: ObservabilityView; onFastTrack: () => void; onRefactor: () => void }) {
  const current = view.operations.currentFeature;
  const debt = view.operations.techDebt;
  const showResourceSignature = observability.showsResourceSignature;
  return <section className="page-panel"><PageHeading eyebrow="COMMUNITY ROADMAP" title="Requirement Timeline" description="기능마다 서로 다른 자원 성향을 가지며, 빠른 출시와 코드 건강성 사이의 트레이드오프도 관리합니다." />{view.hud.launched && <div className="settlement-summary"><span>TECH DEBT · {debt.value}/100</span><strong>{debt.refactoring ? `REFACTORING · ${debt.remainingRefactorDays}D` : `DEV EFF ${pct(debt.developmentModifier)}%`}</strong><small>Incident Risk ×{debt.incidentRiskMultiplier.toFixed(2)} · FAST TRACK은 현재 기능을 30% 당기는 대신 Debt를 쌓고, REFACTOR는 5일간 기능 개발을 멈춰 Debt -30.</small><button className="replica-add" disabled={!debt.canFastTrack || debt.refactoring} onClick={onFastTrack}>⚡ FAST TRACK · +30% PROGRESS</button><button className="replica-add" disabled={debt.value < 10 || debt.refactoring} onClick={onRefactor}>↺ REFACTOR · 5 DAYS · DEBT -30</button></div>}<div className="settlement-summary"><span>OBSERVABILITY · {observability.level}</span><strong>{observability.label}</strong><small>{observability.nextUnlock ?? '요청 추적과 출시 영향 분석까지 모두 해금되었습니다.'}</small></div><div className="phase-board">{([1, 2, 3] as const).map((phase) => <div className="phase-lane" key={phase}><header><span>PHASE {phase}</span><strong>{phase === 1 ? 'EARLY' : phase === 2 ? 'GROWTH' : 'SCALE'}</strong></header><div>{view.features.filter((feature) => feature.phase === phase).map((feature, index) => <article className={`feature-card ${feature.state}`} key={feature.id}><div className="feature-index">{String(index + 1).padStart(2, '0')}</div><span>{feature.state === 'completed' ? '✓' : feature.state === 'developing' ? '●' : feature.state === 'hidden' ? '?' : '○'}</span><strong>{feature.name}</strong><small>DAU {number(feature.threshold)}</small>{feature.state === 'developing' && current && <div className="inline-progress"><div className="progress-track"><i style={{ width: `${pct(current.progress / current.requiredWork)}%` }} /></div><small>{current.elapsedDays}/~{current.elapsedDays + current.estimatedRemainingDays}일 · 약 {current.estimatedRemainingDays}일 남음</small></div>}{feature.route && <div className="feature-route-tags">{feature.route.map((node, nodeIndex) => <i key={`${node}-${nodeIndex}`}>{presentationCatalog.requestNodeLabel(node)}</i>)}</div>}{feature.load && showResourceSignature && <div><i>A {feature.load.app}</i><i>D {feature.load.db}</i><i>Q {feature.load.async}</i><i>S {feature.load.storage}</i></div>}{feature.load && !showResourceSignature && <small>Resource signature · METRICS에서 해금</small>}</article>)}</div></div>)}</div></section>;
}
