import type { GameView, SkillNodeView, SkillRefView } from '../application/game-view';
import { money, pct } from './game-format';
import { PageHeading } from './game-panel';

const CATEGORY_LABEL: Record<SkillRefView['category'], string> = { fundamental: 'FUNDAMENTALS', language: 'LANGUAGE', framework: 'FRAMEWORK', technology: 'TECHNOLOGY' };

export function LearningPanel({ view, onStudy }: { view: GameView; onStudy: (skill: SkillNodeView) => void }) {
  const categories = ['fundamental', 'language', 'framework', 'technology'] as const;
  return <section className="page-panel"><PageHeading eyebrow="DEVELOPER SKILL TREE" title="실전 경험 → 학습 → 레벨업" description="학습 비용은 시작 즉시 CASH에서 차감됩니다. OS & Runtime / Network / Software Design을 올리면 관측 정보도 BASIC → METRICS → APM으로 깊어집니다." /><div className="skill-tree">{categories.map((category) => <div className={`skill-lane ${category}`} key={category}><div className="skill-lane-title"><span>{CATEGORY_LABEL[category]}</span><i /></div><div className="skill-node-grid">{view.skills.filter((skill) => skill.category === category).map((skill) => <button key={skill.key} className={`skill-node ${skill.canStudy ? 'ready' : ''} ${skill.studying ? 'studying' : ''}`} disabled={!skill.canStudy} onClick={() => onStudy(skill)}><span className="skill-icon">{skill.icon}</span><div><strong>{skill.name}</strong><em>Lv.{skill.level}{skill.studying && skill.targetLevel ? ` → ${skill.targetLevel}` : ''}</em></div><div className="skill-exp"><i><b style={{ width: `${skill.requiredExperience ? Math.min(100, Math.round(skill.experienceDays / skill.requiredExperience * 100)) : 100}%` }} /></i><small>{skill.requiredExperience ? `${skill.experienceDays}/${skill.requiredExperience}d EXP` : 'MAX'}</small></div>{skill.studying && <div className="inline-progress"><div className="progress-track"><i style={{ width: `${pct(skill.studyProgress)}%` }} /></div><small>STUDYING · {skill.elapsedStudyDays}/{skill.studyDays}일 · {pct(skill.studyProgress)}%</small></div>}<footer><b>{skill.studying ? 'STUDYING' : skill.canStudy ? 'STUDY' : skill.reason ?? 'LOCKED'}</b><span>{skill.studyDays ? `${skill.studyDays}일 · ${money(skill.cost ?? 0)}` : 'MAX'}</span></footer></button>)}</div></div>)}</div></section>;
}
