import type { GameView, TechnologyOptionView } from '../application/game-view';
import { money, pct } from './game-format';
import { PageHeading } from './game-panel';

export function TechnologyPanel({ view, onBuild }: { view: GameView; onBuild: (tech: TechnologyOptionView) => void }) {
  const groups = [['TRAFFIC', ['ALB']], ['CACHE', ['REDIS']], ['ASYNC', ['SQS', 'RABBITMQ', 'KAFKA']], ['STORAGE', ['OBJECT_STORAGE']]] as const;
  const activeBuild = view.operations.currentTechnologyBuild;
  return <section className="page-panel"><PageHeading eyebrow="TECHNOLOGY CATALOG" title="서비스에 기술 연결" description="구축비는 즉시 CASH에서 빠지고, 월 비용은 매월 정산 때 반영됩니다. 모든 기술에는 해결하는 병목과 감수할 비용/위험이 함께 있습니다." /><div className="technology-groups">{groups.map(([name, ids]) => <div className="technology-group" key={name}><div className="group-label"><span>{name}</span><i /></div><div className="technology-grid">{ids.map((id) => { const tech = view.technologies.find((item) => item.id === id)!; const building = activeBuild?.id === id; const totalDays = building ? activeBuild.elapsedDays + activeBuild.estimatedRemainingDays : 0; return <button className={`technology-card ${tech.deployed ? 'deployed' : ''} ${building ? 'building' : ''}`} key={id} disabled={!tech.available} onClick={() => onBuild(tech)}><div className="tech-top"><span>{tech.icon}</span><em>{tech.deployed ? 'ACTIVE' : building ? 'BUILDING' : tech.available ? 'READY' : 'LOCKED'}</em></div><strong>{tech.name}</strong><p>{tech.preview}<br />✓ {tech.benefits[0]}<br />△ {tech.tradeoffs[0]}</p><div className="tech-numbers"><span><small>즉시 구축비</small><b>{money(tech.buildCost)}</b></span><span><small>월 비용</small><b>{money(tech.monthlyCost)}</b></span><span><small>BASE WORK</small><b>{tech.buildWork}</b></span></div>{building && <div className="inline-progress"><div className="progress-track"><i style={{ width: `${pct(activeBuild.progress / activeBuild.requiredWork)}%` }} /></div><small>{activeBuild.elapsedDays}/~{totalDays}일 · 약 {activeBuild.estimatedRemainingDays}일 남음</small></div>}<div className="tech-action">{tech.deployed ? 'CONNECTED' : building ? 'BUILDING…' : tech.reason ?? 'BUILD →'}</div></button>; })}</div></div>)}</div></section>;
}
